- name: modify repository php5.6
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  when: "{{ php_version | version_compare('5.6', '==') }}"


- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  with_items:
    - "php5.6-fpm"
    - "php5.6-gd"
    - "php5.6-mysql"
    - "php5.6-pgsql"
    - "php5.6-mbstring"
    - "php5.6-curl"
    - "php5.6-xml"    
  notify: restart php5-fpm

- name: modify config
  template:
    src: "{{ item }}"
    dest: "/etc/php/5.6/fpm/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - php-fpm.conf
    - php.ini
  notify: restart php5-fpm

- name: php5.6-fpm is enabled
  service:
    name: php5.6-fpm
    state: started
    enabled: yes
