galaxy_info:
  author: mats116
  description: "MariaDB Server installer"
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  galaxy_tags:
    - mariadb
    - mysql
dependencies: []