- name: modify geocountry.conf
  copy:
    src: geocountry.conf
    dest: /etc/nginx/geocountry.conf
    owner: root
    group: root
    mode: 0644

- name: modify self-signed certificate
  copy:
    src: ssl
    dest: /etc/nginx
    owner: root
    group: root
    mode: 0755
