php_version: "5.5"

# Resource Limits
max_execution_time: 30
max_input_time: 60
memory_limit: 128M

# Data Handling
post_max_size: 8M
always_populate_raw_post_data: 0

# Module Settings
date_timezone: Asia/Tokyo
